### ISSUE TITLE
Class not registered error

### ISSUE THREAD

**Issue by MihaiUdrea** [marb2000/XamlIslands#4]
When creating the app object

> winrt::MyApp::App app;

 I get the error:

> Exception thrown at 0x00007FF9CA2C9129 (KernelBase.dll) in SampleCppApp.exe: WinRT originate error - 0x80040154 : 'Class not registered'.

**Comment by marb2000** [comment]
This is about the sample CppWin32App_With_Island  right. What build and SDK are you using? Xaml Islands is supported with the Windows 10 1903 build, and the SDK 18362.

**Comment by MihaiUdrea** [comment]
My machine was Win10 1809. Thank you for clarifications.
